{% set name = "arabic_reshaper" %}
{% set version = "2.1.1" %}
{% set sha256 = "cf318fa5d51d2d224fa49bf6bdbbb4684f6bd2c068b75cfce0e607f89ac199dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - configparser
    - future
    - setuptools

test:
  imports:
    - arabic_reshaper

about:
  home: https://github.com/mpcabd/python-arabic-reshaper
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Reconstruct Arabic sentences to be used in applications that don't support Arabic
